# Generated by Django 5.1.1 on 2024-10-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
