# Generated by Django 5.1.1 on 2024-10-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_studentprofile_fullname_studentprofile_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='grade',
        ),
    ]
