# Generated by Django 4.2.7 on 2024-10-14 16:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_studentprofile_address_studentprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='media/default_picture.png', max_length=255, verbose_name='image'),
        ),
    ]
